### ISSUE TITLE
能否蓝牙发送整个文件夹

### ISSUE THREAD

**Issue by jerry011235** [drakeet/resources#2]
能否蓝牙发送（或其他方式传输）整个文件夹，而不是只能某篇文章？
app非常棒！赞一个！

另外给[GeekApk](https://geekapk.org/)的建议：
先赶快把论坛上线，可以采用 https://bbs.letitfly.me/ 使用的 [Flarum论坛系统](http://discuss.flarum.org.cn/)。
然后去 [中国独立开发者项目列表](https://github.com/1c7/chinese-independent-developer) 联系下app的作者，邀请他们来论坛发主题帖。
慢慢地就活跃了，当然第一个帖子肯定是纯纯写作😎

**Comment by drakeet** [comment]
感谢，纯纯写作即将支持批量导出和云同步。至于 GeekApk，我没有参与，没有也没有计划，抱歉。
